our_file = "cohort_data.txt"

def unique_houses(filename):
    """TODO: Create a set of student houses.

    Iterates over the cohort_data.txt file to look for all of the included house names
    and creates a set called 'houses' that holds those names.

        ex. houses = set([ "Hufflepuff", 
                    "Slytherin", 
                    "Ravenclaw", 
                    "Gryffindor", 
                    "Dumbledore's Army",
                    "Order of the Phoenix"
            ])
    
    """
    filename = open(filename)
    houses = set()
    for line in filename: 
        data = line.split('|')
        houses.add(data[2])
    return houses

#print unique_houses(our_file)

def sort_by_cohort(filename):
    """TODO: Sort students by cohort.

    Iterates over the data to create a list for each cohort, ordering students
    alphabetically by first name and tas separately. Returns list of lists.

        ex. winter_15 = ["alice tsao", "amanda gilmore", "anne vetto", "..." ]
        ex. all_students = [winter_15, spring_15, summer_15, tas]
    
    """
    filename = open(filename)
    all_students = []
    winter_15 = []
    spring_15 = []
    summer_15 = []
    tas = []

    for student in filename:
        student = student.rstrip()
        updated_student = student.split("|")
        entry = updated_student[0] + " "+ updated_student[1]
        names = entry.lower()
        if updated_student[3] != '':
            if updated_student[4] == "Winter 2015": 
                winter_15.append(names)
            elif updated_student[4] == "Spring 2015":
                spring_15.append(names)
            elif updated_student[4] == "Summer 2015":
                summer_15.append(names)
        else: 
            tas.append(names)
    tas.append("denise wiedl")
    all_students.extend([winter_15, spring_15, summer_15, tas])
    return all_students

#print sort_by_cohort(our_file)





def students_by_house(filename):
    """TODO: Sort students by house.

    Iterate over the data to create a list for each house, and sort students
    into their appropriate houses by last name. Sort TAs into a list called "tas".
    Return all lists in one list of lists.
        ex. hufflepuff = ["Gaikwad", "Le", "..." ]
        ex. tas = ["Bryant", "Lefevre", "..."]
        ex. houses_tas = [ hufflepuff, 
                        gryffindor, 
                        ravenclaw, 
                        slytherin, 
                        dumbledores_army,
                        order_of_the_phoenix,
                        tas 
            ]
    """
    filename = open(filename)
    all_students = []
    gryffindor = []
    hufflepuff = []
    slytherin = []
    dumbledores_army = []
    order_of_the_phoenix = []
    ravenclaw = []
    tas = []

    for student in filename:
        student = student.rstrip()
        updated_student = student.split("|")

        if updated_student[3] != "":
            if updated_student[2] == "Slytherin":
                slytherin.append(updated_student[1])
            elif updated_student[2] == "Hufflepuff":
                hufflepuff.append(updated_student[1])
            elif updated_student[2] == "Gryffindor":
                gryffindor.append(updated_student[1])
            elif updated_student[2] == "Dumbledore's Army":
                dumbledores_army.append(updated_student[1])
            elif updated_student[2] == "Order of the Phoenix":
                order_of_the_phoenix.append(updated_student[1])
            elif updated_student[2] == "Ravenclaw":
                ravenclaw.append(updated_student[1])
        else:
            tas.append(updated_student[1])
    tas.append("Wiedl")
    all_students.extend([gryffindor, hufflepuff, slytherin, ravenclaw, dumbledores_army, order_of_the_phoenix, tas])    
    return all_students


#print students_by_house(our_file)

def all_students_tuple_list(filename):
    """TODO: Create a list of tuples of student data.

    Iterates over the data to create a big list of tuples that individually
    hold all the data for each person. (full_name, house, advisor, cohort)
        ex. all_people = [
                ("Alice Tsao", "Slytherin", "Kristen", "Winter 2015"),
                ("Amanda Gilmore", "Hufflepuff", "Meggie", "Winter 2015"),
                # ...
            ]
    """
    student_list = []
    data = open(filename)
    for line in data: 
        line = line.rstrip().split("|")
        if line[3] != "":
            line = [line[0] + " " + line[1]] + line[2:]
            student_list.append(tuple(line))
    return student_list

list_of_students = all_students_tuple_list(our_file)   
#print list_of_students

def find_cohort_by_student_name(student_list):
    """TODO: Given full name, return student's cohort.

    Use the above list of tuples generated by the preceding function to make a small
    function that, given a first and last name, returns that student's cohort, or returns
    'Student not found.' when appropriate. """
    name = raw_input("Enter student name: ")
    
    for student in student_list:
        if student[0] == name:
            return student[3]
    return "Student not found."

print find_cohort_by_student_name(list_of_students)

##########################################################################################
# Further Study Questions


def find_name_duplicates(filename):
    """TODO: Using set operations, make a set of student first names that have duplicates.

    Iterates over the data to find any first names that exist across multiple cohorts. 
    Uses set operations (set math) to create a set of these names. 
    NOTE: Do not include staff -- or do, if you want a greater challenge. 

       ex. duplicate_names = set(["Sarah"])

    """

    duplicate_names = set()

    # Code goes here

    return duplicate_names


def find_house_members_by_student_name(student_list):
    """TODO: Create a function that, when given a name, returns everyone in
    their house that's in their cohort.

    Use the list of tuples generated by all_students_tuple_list to make a small function that,
    when given a student's first and last name, returns students that are in both that
    student's cohort and that student's house."""

    # Code goes here

    return

